"""PDF Report Generator using ReportLab."""
import os
import json
from datetime import datetime
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image as RLImage, PageBreak
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from flask import current_app
from app.database.db import get_db


SEVERITY_COLORS = {
    "critical": colors.HexColor("#dc2626"),
    "high":     colors.HexColor("#ea580c"),
    "medium":   colors.HexColor("#d97706"),
    "low":      colors.HexColor("#16a34a"),
}


def generate_pdf(session_id: int) -> str:
    """Generate a PDF report for a test session. Returns the PDF file path."""
    db      = get_db()
    session = db.execute(
        """SELECT ts.*, u.username, u.email FROM test_sessions ts
           JOIN users u ON ts.user_id = u.id WHERE ts.id = ?""",
        (session_id,)
    ).fetchone()
    bugs = db.execute(
        "SELECT * FROM bug_reports WHERE session_id = ? ORDER BY confidence DESC",
        (session_id,)
    ).fetchall()

    report_dir = current_app.config["REPORT_FOLDER"]
    os.makedirs(report_dir, exist_ok=True)
    pdf_path = os.path.join(report_dir, f"report_session_{session_id}.pdf")

    doc    = SimpleDocTemplate(pdf_path, pagesize=A4,
                                leftMargin=0.75*inch, rightMargin=0.75*inch,
                                topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    story  = []

    # ── Header ────────────────────────────────────────────────────────────────
    title_style = ParagraphStyle("title", parent=styles["Title"],
                                  textColor=colors.HexColor("#1e293b"),
                                  fontSize=20, spaceAfter=6, alignment=TA_CENTER)
    story.append(Paragraph("CNN Visual Debugging Report", title_style))
    story.append(Paragraph(
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        ParagraphStyle("sub", fontSize=9, textColor=colors.grey, alignment=TA_CENTER)
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=12))

    # ── Session Info ──────────────────────────────────────────────────────────
    story.append(Paragraph("Session Summary", styles["Heading2"]))
    info_data = [
        ["Session ID", str(session_id)],
        ["Target URL", dict(session)["target_url"]],
        ["Status",     dict(session)["status"].upper()],
        ["Analyst",    dict(session)["username"]],
        ["Bugs Found", str(dict(session)["bugs_found"])],
        ["Accuracy",   f"{(dict(session)['accuracy'] or 0)*100:.1f}%"],
    ]
    info_table = Table(info_data, colWidths=[2*inch, 4.5*inch])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 9),
        ("GRID",       (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("PADDING",    (0, 0), (-1, -1), 6),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 16))

    # ── Bug Reports Table ─────────────────────────────────────────────────────
    story.append(Paragraph("Detected Bugs", styles["Heading2"]))
    if bugs:
        headers = ["#", "Bug Type", "Severity", "Confidence", "Description"]
        rows    = [headers]
        for i, bug in enumerate(bugs, 1):
            rows.append([
                str(i),
                bug["bug_type"].capitalize(),
                bug["severity"].upper(),
                f"{bug['confidence']*100:.1f}%",
                (bug["description"] or "—")[:60],
            ])
        bug_table = Table(rows, colWidths=[0.3*inch, 1*inch, 0.8*inch, 0.9*inch, 3.5*inch])
        bug_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("PADDING",    (0, 0), (-1, -1), 5),
        ]))
        story.append(bug_table)
    else:
        story.append(Paragraph("No bugs detected in this session.", styles["Normal"]))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    story.append(Paragraph(
        "Generated by CNN Visual Debugger — AI-Powered UI Testing",
        ParagraphStyle("footer", fontSize=8, textColor=colors.grey, alignment=TA_CENTER)
    ))

    doc.build(story)
    return pdf_path
